# https://mypy.readthedocs.io/en/stable/config_file.html
[[tool.mypy.overrides]]
module = [
    "pandas",
    "geopandas",
    "rioxarray",
    "shapely"
]
ignore_missing_imports = true

[tool.isort]
profile = "black"
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
use_parentheses = true
filter_files = true

[tool.flake8]
max-line-length = 88
max-complexity = 10
exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "*.egg-info",
    ".pytest_cache",
    ".mypy_cache"
]
ignore = [  # alertas e erros por conta do black
    "E501", # linha longa
    "E203", # espaço antes de ':'
    "E225", # sem espaço ao redor de operadores 
    "W503", # quebra de linha antes de um operador binário
    "W504", # quebra de linha após um operador binário line
    "E402"  # imports não concentrados no topo: deixe o Isort cuidar disso
]

[tool.pydocstyle]
convention = "numpy"
add-ignore = "D401"
match = '(?!test_|tests).*\.py'  # ignora arquivos python contendo "test_" ou "tests"
match-dir = "[^\tests|.].*"  # ignora diretórios iniciados com "." ou "tests"