name: nuvem
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.1
  - alsa-lib=1.2.6.1
  - anyio=3.6.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attr=2.5.1
  - attrs=21.4.0
  - babel=2.10.3
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - black=22.6.0
  - bleach=5.0.1
  - blosc=1.21.1
  - bokeh=2.4.3
  - boost-cpp=1.74.0
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - cartopy=0.20.3
  - certifi=2022.6.15
  - cffi=1.15.0
  - cfgrib=0.9.10.1
  - cfitsio=4.1.0
  - charset-normalizer=2.1.0
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.1.0
  - cryptography=37.0.2
  - curl=7.83.1
  - cycler=0.11.0
  - cytoolz=0.11.2
  - dask=2022.7.0
  - dask-core=2022.7.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2022.7.0
  - eccodes=2.26.0
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.8
  - fftw=3.3.10
  - findlibs=0.0.2
  - fiona=1.8.21
  - flake8=4.0.1
  - flit-core=3.7.1
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - freeglut=3.2.2
  - freetype=2.10.4
  - freexl=1.0.6
  - fsspec=2022.5.0
  - gdal=3.5.1
  - geopandas=0.11.0
  - geopandas-base=0.11.0
  - geos=3.11.0
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.70.2
  - glib-tools=2.70.2
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - importlib_resources=5.8.0
  - iniconfig=1.1.1
  - ipykernel=6.15.0
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - isort=5.10.1
  - jack=1.9.18
  - jasper=2.0.33
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - json-c=0.16
  - json5=0.9.5
  - jsonschema=4.6.1
  - jupyter_client=7.0.6
  - jupyter_core=4.10.0
  - jupyter_server=1.18.0
  - jupyterlab=3.4.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.14.0
  - kealib=1.4.15
  - keyutils=1.6.1
  - kiwisolver=1.4.3
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.64
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libcurl=7.83.1
  - libdap4=3.20.6
  - libdb=6.2.32
  - libdeflate=1.12
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.3.4
  - libgcc-ng=12.1.0
  - libgdal=3.5.1
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.70.2
  - libglu=9.0.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.4
  - librttopo=1.1.0
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libudev1=249
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzip=1.9.2
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - locket=1.0.0
  - lz4=4.0.0
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - msgpack-python=1.0.4
  - munch=2.5.0
  - munkres=1.1.4
  - mypy=0.961
  - mypy_extensions=0.4.3
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbclassic=0.3.7
  - nbclient=0.6.6
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.8.4
  - notebook=6.4.12
  - notebook-shim=0.1.0
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.0
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pathspec=0.9.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=21.2.4
  - pixman=0.40.0
  - platformdirs=2.5.1
  - pluggy=1.0.0
  - poppler=22.04.0
  - poppler-data=0.4.11
  - portaudio=19.6.0
  - postgresql=14.4
  - proj=9.0.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=14.0
  - pure_eval=0.2.2
  - py=1.11.0
  - pycodestyle=2.8.0
  - pycparser=2.21
  - pydantic=1.9.1
  - pydocstyle=6.1.1
  - pyflakes=2.4.0
  - pygments=2.12.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyproj=3.3.1
  - pyqt=5.15.4
  - pyrsistent=0.18.1
  - pyshp=2.3.0
  - pysocks=1.7.1
  - pytest=7.1.2
  - python=3.10.5
  - python-dateutil=2.8.2
  - python-eccodes=1.4.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.10
  - pytz=2022.1
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt-main=5.15.4
  - rasterio=1.2.10
  - readline=8.1.2
  - requests=2.28.1
  - rioxarray=0.11.1
  - rtree=1.0.0
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - send2trash=1.8.0
  - setuptools=61.2.0
  - shapely=1.8.2
  - sip=6.5.1
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.3.1
  - sqlite=3.39.0
  - stack_data=0.3.0
  - tblib=1.7.0
  - terminado=0.15.0
  - threadpoolctl=3.1.0
  - tiledb=2.9.5
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.1
  - traitlets=5.3.0
  - typed-ast=1.5.4
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzcode=2022a
  - tzdata=2022a
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.3
  - wheel=0.37.1
  - xarray=2022.3.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.3
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2022.6.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - pyqt5-sip==12.9.0
    - timeless==0.2.3
